### ISSUE TITLE
Hello dear friend, why did you delete the Pump Bot? :/

### ISSUE THREAD

**Issue by tsebis** [neseleznev/ulg-mscn#1]
Hello dear friend, why did you delete the Pump Bot? :/

**Comment by neseleznev** [comment]
There were so many issues that took possible troubles with gaining profits to people, so I decided it's too rare. Moreover, I'm on exams now and have no time to fix some of them. If you're interested, don't hesitate to write me ne.seleznev@gmai.com , I'll provide you the latest repo snapshot

**Comment by tsebis** [comment]
i've sent a email for you, dnt got any response yet
